I just used @musixmatch to discover T.N.T. by AC/DC #lyrics http://lyr.cx/t/14647763 
 #9829  T.N.T. by AC/DC #lastfm: http://bit.ly/TBB0 
listening to   AC/DC   TNT lyrics     http://blip.fm/ 1bqkup 
I wait for the day SMKDJ's Dynamitez use AC/DC's TNT as their song.
AC/DC   T.N.T   Live At River Plate   HD http://www.rockspaceone.com.br/videos.php v 535   via @rockspaceone
TNT AC/DC with lyrics: http://youtu.be/pR30knJs4Xk  via @youtube
Listening to   AC DC    T.N.T. #nowplaying
